---
# CIS Benchmarks Section 5

  - name: 5.1.1 Install the rsyslog package
    yum: name=rsyslog state=present
  - name: 5.1.2 Activate the rsyslog Service
    service: name=rsyslog enabled=yes state=started
  - name: 5.1.3 Configure /etc/rsyslog.conf
    copy: src=etc/rsyslog.conf dest=/etc/rsyslog.conf owner=root group=root mode=0644
  - name: 5.1.4 Create and Set Permissions on rsyslog Log Files
    file: path=/var/log/{{ item }} state=touch owner=root group=wheel mode=0640
    with_items:
        - messages
        - kern.log
        - daemon.log
        - syslog
        - unused.log
  - name: 5.1.5 Configure rsyslog to Send Logs to a Remote Log Host
    lineinfile: state=present regexp="^\*\.\*" line="*.* @@{{ rsyslog_dest }}"
    when: rsyslog_dest is defined
  - name: 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts
    lineinfile: state=present line="$ModLoad imtcp.so"
    when: rsyslog_host
  - name: 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts
    lineinfile: state=present line="$InputTCPServerRun 514"
    when: rsyslog_host
  - name: 5.2.1.1 Configure Data Retention
    lineinfile: state=present dest=/etc/audit/auditd.conf regexp="^max_log_file =" line="max_log_file = {{ max_log_file }}"
    notify: Reload auditd Rules
  - name: 5.2.1.2 Disable System on Audit Log Full
    lineinfile: state=present dest=/etc/audit/auditd.conf regexp="^space_left_action =" line="space_left_action = {{ space_left_action }}"
    notify: Reload auditd Rules
  - name: 5.2.1.2 Disable System on Audit Log Full
    lineinfile: state=present dest=/etc/audit/auditd.conf regexp="^action_mail_acct =" line="action_mail_acct = {{ action_mail_acct }}"
    notify: Reload auditd Rules
  - name: 5.2.1.2 Disable System on Audit Log Full
    lineinfile: state=present dest=/etc/audit/auditd.conf regexp="^admin_space_left_action =" line="admin_space_left_action = {{ admin_space_left_action }}"
    notify: Reload auditd Rules
  - name: 5.2.1.3 Keep All Auditing Information
    lineinfile: state=present dest=/etc/audit/auditd.conf regexp="^max_log_file_action =" line="max_log_file_action = {{ max_log_file_action }}"
    notify: Reload auditd Rules
  - name: 5.2.2 Enable auditd Service
    service: name=auditd enabled=yes state=running
  - name: 5.2.3 Enable Auditing for Processes That Start Prior to auditd
    lineinfile: state=present dest=/etc/grub.conf backrefs=yes regexp="(^\s*kernel.*)$(?<!audit=1)" line="\1 audit=1"
  - name: 5.2.4 - 5.2.18 Configure auditd Rules
    copy: src=etc/audit/audit.rules dest=/etc/audit/audit.rules
    notify: Reload auditd Rules
  - name: 5.3 Configure logrotate
    copy: src=etc/logrotate.d/syslog dest=/etc/logrotate.d/syslog
